#
###################################
# Site wide configuration
####################################
#
title:       "IceLeng's blog"
description: 'A backend developer and operator who loves design awesome things. Working for HW in ShenZhen, China.'
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          China/ShenZhen
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: IceLeng
  avatar: beauty.jpg
  job: "Operation Engineer"
  bio: "A backend developer and operator who loves design awesome things. Working for HW in ShenZhen, China."
  email: iceprogrammer@sohu.com
  disqus-shortname: renyuanzblog
  twitter: alittlered3 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: iceleng #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
